"""
Knowledge base manager for Obsidian Brain MCP.

Generates and manages a persistent Markdown file containing comprehensive
vault information for LLM context across sessions.
"""

from datetime import datetime

from .models import FolderNode, NoteMetadata, VaultStats, VaultStructure

# Fixed path within the vault for the knowledge base
KNOWLEDGE_BASE_PATH = ".obsidian-brain/knowledge-base.md"


class KnowledgeBaseManager:
    """
    Manages the persistent vault knowledge base file.

    The knowledge base is a Markdown file stored in the vault that provides
    comprehensive context about vault structure, tags, and connections.
    """

    def __init__(self):
        self.path = KNOWLEDGE_BASE_PATH

    def generate_content(
        self,
        structure: VaultStructure,
        include_orphans: bool = True,
        include_link_patterns: bool = True,
    ) -> str:
        """
        Generate the complete knowledge base Markdown content.

        Args:
            structure: The cached vault structure
            include_orphans: Include list of orphan notes
            include_link_patterns: Include link analysis section

        Returns:
            Complete Markdown content for the knowledge base
        """
        sections = [
            self._build_frontmatter(structure.stats),
            self._build_header(),
            self._build_overview(structure.stats),
            self._build_folder_tree(structure.folders),
            self._build_tag_taxonomy(structure.notes),
            self._build_hub_notes(structure.notes),
        ]

        if include_link_patterns:
            sections.append(self._build_link_patterns(structure.notes))

        if include_orphans:
            sections.append(self._build_orphan_notes(structure.notes))

        sections.append(self._build_footer())

        return "\n\n".join(sections)

    def _build_frontmatter(self, stats: VaultStats) -> str:
        """Build YAML frontmatter with metadata."""
        now = datetime.now().isoformat()
        return f"""---
created: {now}
updated: {now}
generator: obsidian-brain-mcp
vault_stats:
  total_notes: {stats.total_notes}
  total_folders: {stats.total_folders}
  total_tags: {stats.total_tags}
  total_links: {stats.total_links}
  orphan_notes: {stats.orphan_notes}
---"""

    def _build_header(self) -> str:
        """Build the document header."""
        return """# Vault Knowledge Base

> This file is auto-generated by Obsidian Brain MCP. It provides a comprehensive
> overview of your vault structure to help LLMs understand and navigate your knowledge base.
>
> **Regenerate this file** when your vault structure changes significantly by calling
> the `create_vault_knowledge_base` tool."""

    def _build_overview(self, stats: VaultStats) -> str:
        """Build the overview statistics section."""
        return f"""## Overview

| Metric | Count |
|--------|-------|
| Notes | {stats.total_notes} |
| Folders | {stats.total_folders} |
| Tags | {stats.total_tags} |
| Links | {stats.total_links} |
| Orphans | {stats.orphan_notes} |"""

    def _build_folder_tree(self, folders: list[FolderNode]) -> str:
        """Build the folder structure tree."""
        lines = ["## Folder Structure", "", "```"]

        def render_folder(folder: FolderNode, prefix: str = "", is_last: bool = True) -> list[str]:
            """Recursively render folder tree with ASCII art."""
            result = []
            connector = "└── " if is_last else "├── "
            result.append(f"{prefix}{connector}{folder.name}/")

            child_prefix = prefix + ("    " if is_last else "│   ")
            for i, child in enumerate(folder.children):
                is_child_last = i == len(folder.children) - 1
                result.extend(render_folder(child, child_prefix, is_child_last))

            return result

        # Root level
        lines.append("/")
        for i, folder in enumerate(folders):
            is_last = i == len(folders) - 1
            lines.extend(render_folder(folder, "", is_last))

        lines.append("```")
        return "\n".join(lines)

    def _build_tag_taxonomy(self, notes: list[NoteMetadata]) -> str:
        """Build the tag taxonomy section."""
        # Count tags
        tag_counts: dict[str, int] = {}
        tag_examples: dict[str, str] = {}

        for note in notes:
            for tag in note.tags:
                tag_counts[tag] = tag_counts.get(tag, 0) + 1
                if tag not in tag_examples:
                    tag_examples[tag] = note.path

        # Sort by count descending
        sorted_tags = sorted(tag_counts.items(), key=lambda x: -x[1])

        lines = ["## Tag Taxonomy", ""]

        if not sorted_tags:
            lines.append("*No tags found in vault.*")
            return "\n".join(lines)

        # Top 20 tags
        lines.append("### Top Tags by Usage")
        lines.append("")
        lines.append("| Rank | Tag | Count | Example Note |")
        lines.append("|------|-----|-------|--------------|")

        for i, (tag, count) in enumerate(sorted_tags[:20], 1):
            example = tag_examples.get(tag, "")
            lines.append(f"| {i} | #{tag} | {count} | {example} |")

        # Tag hierarchy (inferred from / separator)
        hierarchical_tags = [t for t in tag_counts if "/" in t]
        if hierarchical_tags:
            lines.append("")
            lines.append("### Hierarchical Tags")
            lines.append("")

            # Group by root
            roots: dict[str, list[tuple[str, int]]] = {}
            for tag in hierarchical_tags:
                root = tag.split("/")[0]
                if root not in roots:
                    roots[root] = []
                roots[root].append((tag, tag_counts[tag]))

            for root, children in sorted(roots.items()):
                lines.append(f"- **#{root}**")
                for tag, count in sorted(children, key=lambda x: -x[1]):
                    lines.append(f"  - #{tag} ({count})")

        return "\n".join(lines)

    def _build_hub_notes(self, notes: list[NoteMetadata]) -> str:
        """Build the hub notes section (most connected notes)."""
        # Calculate connectivity score
        scored_notes = []
        for note in notes:
            incoming = len(note.incoming_links)
            outgoing = len(note.outgoing_links)
            total = incoming + outgoing
            if total > 0:
                scored_notes.append((note, incoming, outgoing, total))

        # Sort by total connections
        scored_notes.sort(key=lambda x: -x[3])

        lines = ["## Hub Notes (Most Connected)", ""]

        if not scored_notes:
            lines.append("*No connected notes found.*")
            return "\n".join(lines)

        lines.append("Notes with highest connectivity (incoming + outgoing links):")
        lines.append("")
        lines.append("| Note | Title | Incoming | Outgoing | Total |")
        lines.append("|------|-------|----------|----------|-------|")

        for note, incoming, outgoing, total in scored_notes[:15]:
            lines.append(f"| {note.path} | {note.title} | {incoming} | {outgoing} | {total} |")

        return "\n".join(lines)

    def _build_link_patterns(self, notes: list[NoteMetadata]) -> str:
        """Build the link patterns section."""
        lines = ["## Link Patterns", ""]

        # Most referenced (most backlinks)
        by_incoming = sorted(notes, key=lambda n: -len(n.incoming_links))
        referenced = [(n.path, len(n.incoming_links)) for n in by_incoming if n.incoming_links]

        if referenced:
            lines.append("### Most Referenced Notes")
            lines.append("Notes that are linked TO most frequently:")
            lines.append("")
            for i, (path, count) in enumerate(referenced[:10], 1):
                lines.append(f"{i}. **{path}** ({count} backlinks)")

        # Most linking (most outgoing)
        by_outgoing = sorted(notes, key=lambda n: -len(n.outgoing_links))
        linking = [(n.path, len(n.outgoing_links)) for n in by_outgoing if n.outgoing_links]

        if linking:
            lines.append("")
            lines.append("### Most Linking Notes")
            lines.append("Notes that link OUT to many other notes:")
            lines.append("")
            for i, (path, count) in enumerate(linking[:10], 1):
                lines.append(f"{i}. **{path}** ({count} outgoing)")

        if not referenced and not linking:
            lines.append("*No link patterns found.*")

        return "\n".join(lines)

    def _build_orphan_notes(self, notes: list[NoteMetadata]) -> str:
        """Build the orphan notes section."""
        orphans = [
            note.path for note in notes
            if not note.incoming_links and not note.outgoing_links
        ]

        lines = ["## Orphan Notes", ""]

        if not orphans:
            lines.append("*No orphan notes found. All notes are connected!*")
            return "\n".join(lines)

        lines.append(f"Notes with no incoming or outgoing links ({len(orphans)} total):")
        lines.append("")

        # Show first 20 orphans
        for path in sorted(orphans)[:20]:
            lines.append(f"- `{path}`")

        if len(orphans) > 20:
            lines.append(f"- *...and {len(orphans) - 20} more*")

        return "\n".join(lines)

    def _build_footer(self) -> str:
        """Build the document footer."""
        now = datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
        return f"""---

*Generated by Obsidian Brain MCP on {now}*"""


# Global singleton instance
knowledge_manager = KnowledgeBaseManager()
